Riportate modifiche dal master fino al commit '1ba7c06e11dc08bcde28042ca57edf6f5d1fc278'
Squashed commit of the following:

commit 1ba7c06e11dc08bcde28042ca57edf6f5d1fc278
Author: Andrea Poli <andreapoli80@gmail.com>
Date:   Fri Aug 27 09:30:01 2021 +0200

    [Testsuite]
    Corretti errori rilevati dalla testsuite 'token.attribute_authority.RestTest' relativi a log differenti registrati sui vari A.S. (tomcat/wildfly)

commit c7a94e2b3786561af716c9cd3486c30df6068e96
Author: Andrea Poli <andreapoli80@gmail.com>
Date:   Thu Aug 26 16:31:45 2021 +0200

    [GovWayConsole]
    La creazione di un nuovo gruppo, in una erogazione non andava a buon fine se durante la creazione veniva scelto di ereditare le configurazioni di un gruppo non predefinito, configurato per utilizzare un connettore ridefinito con consegna multipla.

commit af698c2bfff4750a6b260af1fece3eb03f255dc2
Author: Andrea Poli <andreapoli80@gmail.com>
Date:   Thu Aug 26 15:30:32 2021 +0200

    [GovWayConsole]
    Nella maschera di dettaglio di una erogazione o fruizione, in presenza di un connettore di lunghezza superiore ai 150 caratteri viene visualizzata una informazione troncata contenente il suffisso ' ...'.
    Lo stesso accorgimento è stato adottato nelle liste degli header HTTP e dei parametri della URL configurabili nelle trasformazioni.

commit b5bd4ca384ffd324fa8ffe3ce2d9dca4649aa34d
Author: Andrea Poli <andreapoli80@gmail.com>
Date:   Thu Aug 26 12:10:01 2021 +0200

    [ApiRsConfigurazione]
    È adesso possibile censire Attribute Authority anche attraverso le API di configurazione.

commit 5c2a36ae7440c884dfb5c01639d41cddfe251cab
Author: Andrea Poli <andreapoli80@gmail.com>
Date:   Wed Aug 25 18:09:28 2021 +0200

    [GovWayConsole, GovWayMonitor]
    Risolto bug che non consentiva l'associazione di ruoli ad un applicativo server in cui era stata abilitata l'opzione 'Utilizzabile come Client'.
    Gli applicativi server, utilizzabili anche come client, non venivano inoltre riportati nemmeno nella lista degli applicativi fornita dalla tipologia di ricerca per applicativo nella console di monitoraggio.

commit a98b228d27c84f3a168075a7504c8136e09eaa50
Author: Andrea Poli <andreapoli80@gmail.com>
Date:   Wed Aug 25 14:49:02 2021 +0200

    [GovWayCore, GovWayConsole]
    È adesso possibile censire Attribute Authority che consentono di definire politiche di controllo degli accessi basate sugli attributi.
    Nell'intervento è stato aggiunto il tipo di errore 'ConnectorNotFound' utilizzato per identificare la casistica in cui non è stato possibile individuare il connettore che implementa l'API.

commit 53a9e3fdd1e066caba6a7ad8f0e2be7383273a7a
Author: Giuliano Pintori <pintori@link.it>
Date:   Mon Aug 23 18:57:25 2021 +0200

    [GovWayConsole]
    Gli spazi che separano i subtitle nei criteri di ricerca sono adesso i medesimi in entrambi gli stati espansi e chiusi.

commit edb59a97d5af1f4243b83da279b4bad0d1638816
Author: Andrea Poli <andreapoli80@gmail.com>
Date:   Mon Aug 23 18:53:23 2021 +0200

    [Documentazione]
    Aggiunta documentazione per AttributeAuthority

commit e51ef82e2dce4ac184a8cc0b4d77976a8c85187c
Author: Giuliano Pintori <pintori@link.it>
Date:   Mon Aug 23 18:46:42 2021 +0200

    [GovWayConsole, GovWayMonitor]
    Realizzati i seguenti miglioramenti per l'usabilità delle console:
    - Sulla console di monitoraggio, nello storico delle transazioni, dopo aver effettuato una ricerca e aver presentato i risultati viene adesso fornita la possibilità di effettuare una nuova ricerca, con i medesimi criteri, senza dover riaprire il filtro attraverso un pulsante di refresh posto accanto alla lente che consente di riaprire il filtro di ricerca.
    - Sulla console di gestione, nei filtri di ricerca, è adesso possibbile espandere o richiudere i criteri di ricerca relative alle sotto-sezioni.  Il criterio di espandere o richiedere le sezioni è inoltra stata riportata nella maschera di configurazione relativa al Controllo degli Accessi di una erogazione o fruizione di API.

    Squashed commit of the following:

    commit 7156fa6cfa3952a5d8673361c87e3e6af28aca61
    Author: Giuliano Pintori <pintori@link.it>
    Date:   Mon Aug 2 18:00:41 2021 +0200

        [GovwayConsole]
        Aggiunto supporto per l'apertura e chiusura delle sezioni dei filtri di ricerca e delle sezioni delle form di configurazione.

    commit deb1d780913e6483c7af70751f780bff1a0d3756
    Author: Giuliano Pintori <pintori@link.it>
    Date:   Mon Jul 26 11:30:00 2021 +0200

        [GovwayMonitor]
        Aggiunta Icona per ricaricare la ricerca senza aprire il form di ricerca.

        [GovwayConsole]
        Aggiunta apertura e chiusura delle sezioni dei filtri di ricerca.

commit 006ea5f157bae2b651916bfb82fef65c4402caf0
Author: Andrea Poli <andreapoli80@gmail.com>
Date:   Mon Aug 23 10:58:49 2021 +0200

    [GovWayCore]
    Corretti errori rilevati dalla testsuite del profilo 'SPCoop' relativi all'introduzione del supporto delle Attribute Authorities.

commit ce61ded1be9c8ee00f1b727f464ccf998b44bae8
Author: Andrea Poli <andreapoli80@gmail.com>
Date:   Fri Aug 6 18:48:31 2021 +0200

    [GovWayCore, GovWayMonitor, GovWayConsole]
    Predisposto lavoro per AttributeAuthority

commit ce2f1de0c38ddc332b908a6c8c0a8c00d0f0b567
Author: Andrea Poli <andreapoli80@gmail.com>
Date:   Tue Aug 3 18:14:57 2021 +0200

    Risolto alert 'https://github.com/link-it/govway/security/dependabot/mvn/dependencies/commons/pom.xml/org.apache.commons:commons-compress/open' aggiornando alla versione 1.21
    Risolto alert 'https://github.com/link-it/govway/security/dependabot/mvn/dependencies/antinstaller/pom.xml/org.apache.ant:ant/open' aggiornando alla versione 1.10.11

commit dfa470233783bcf4ad536351406ade872d79608b
Author: Andrea Poli <andreapoli80@gmail.com>
Date:   Mon Aug 2 17:28:02 2021 +0200

    [GovWayCore]
    Migliorati log emessi in casi di errore avvenuto durante l'aggiornamento dell'esito della consegna di un connettore multiplo o durante l'aggiornamento della transazione che raggruppa le varie consegne multiple.

commit 9ead8576a3921318228725074769c4252624ba8f
Author: Andrea Poli <andreapoli80@gmail.com>
Date:   Thu Jul 29 17:40:24 2021 +0200

    [ProtocolloSDI]
    Nel caso di fatture P7M, nel formato PEM, contenenti i prefissi -----BEGIN e -----END il software non era in grado di parsare la fattura se si abilitavano i controlli che lo richiedevano (ad esempio abilitando la proprietà 'org.openspcoop2.protocol.sdi.accesso.campiFattura.enable' nel file esterno 'sdi_local.properties'.

commit e3ee7d86af5ed62f98340a9c23c96b803c96ac4b
Author: Andrea Poli <andreapoli80@gmail.com>
Date:   Wed Jul 28 18:51:39 2021 +0200

    [GovWayCore]
    La registrazione della transazione falliva, con l'errore riportato di seguito, se l'erogazione era configurata con molti connettori multipli:
    org.openspcoop2.generic_project.exception.ServiceException: ERRORE: il valore è troppo lungo per il tipo character varying(2000)

commit 67d2f39b3f3304f7f82d87c34dc25195fb6f2c66
Author: Giuliano Pintori <pintori@link.it>
Date:   Mon Jul 26 18:33:05 2021 +0200

    [GovWayConsole]
    Utilizzando il browser IE11 quando si selezionava un filtro di ricerca, al momento del reload della pagina, l'applicazione si bloccava.
    La console del browser indicava il seguente errore: "Errore: L'oggetto non supporta la proprietà o il metodo 'endsWith'"